change some images
Priyansh61/Socialisthan pull request #1
Opened 2024-11-21 10:15 UTC by rohitsingh7568

change the commit and some images and add some log

2024-11-21 10:29 UTC, Priyansh61 requested changes

2024-11-21 10:29 UTC, Priyansh61 commented on src/components/sections/AssociatedPartners.tsx
> +  { name: "MarketPro", logo: "/images/mishi media solution.png" },
Add names relevant to the company logos

2024-11-21 10:29 UTC, Priyansh61 commented on src/components/sections/GetInTouch.tsx
> +          href="https://whatsapp.com/channel/0029VavEHHh0Qealmt5Vbd0o"
Open a new tab use `target = "_blank"` helps to open in a new tab

2024-11-21 10:29 UTC, Priyansh61 commented on src/components/sections/Services.tsx
> +    icon: Video
Align the last line in the center.

2024-11-21 10:29 UTC, Priyansh61 commented on src/components/sections/Testemonial.tsx
Compress the images and use same scale size like 120*120

2024-11-21 10:29 UTC, Priyansh61 commented on src/components/layout/Footer.tsx
> +                src="/images/logo.svg" // Replace with your logo path
Add the new without background logo here

2024-11-22 09:30 UTC, rohitsingh7568 commented
changes some link

2024-11-23 08:20 UTC, merged